## Financial Statement Analysis
#### Link : https://sds-platform-private.s3-us-east-2.amazonaws.com/uploads/P4-Section3-Homework-Challenge.pdf

In [1]:
#Finacial Statement Analysis
#Data for 12 months

revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]


In [2]:
#Import Numpy to make the arithetical operations easier
import numpy as np

#Profit for each month
rev = np.array(revenue)
exp = np.array(expenses)

rev - exp

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [4]:
#Profit after tax (30% tax rate)

tax = 0.30*rev
revaftertax = rev-tax
profitaftertax = revaftertax - exp
profitaftertax

array([-1849.677,  -370.548, -6291.213, -5666.933, -3017.515,  4833.608,
        4761.666,  1015.143,   236.794, -6552.638, -2554.591,  6999.49 ])

In [5]:
#Profit Margin - profit after tax divided by revenue in %

pMargin = (profitaftertax/rev)*100
pMargin

array([-12.69119537,  -4.87149081, -73.05671197, -61.76217738,
       -37.44442307,  59.63412227,  41.41918951,  10.39456937,
         2.29778406, -45.56784581, -23.84355192,  45.35257719])

In [28]:
#good months - where the profit after tax was greater than the mean for the year
mean = round(sum(profitaftertax)/12) #calculating the mean of profit after tax

#Checking for months with a profit after tax greater that the mean

good_months = list(filter(lambda x:x>mean,profitaftertax))

np.around(np.array(good_months),2)

array([-370.55, 4833.61, 4761.67, 1015.14,  236.79, 6999.49])

In [27]:
#bad months - where the profit after tax was less than the mean for the year

#Checking for months with a profit after tax greater that the mean

bad_months = list(filter(lambda x:x<mean,profitaftertax))

np.around(np.array(bad_months),2)

array([-1849.68, -6291.21, -5666.93, -3017.51, -6552.64, -2554.59])

In [10]:
#the best month - where the profit after tax was max for the year

round(max(profitaftertax))

6999

In [11]:
#the worst month - where the profit after tax was min for the year

round(min(profitaftertax))

-6553